name: Aktualisiere ICS

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Generate calendars
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Generate ICS files
        run: python generate_ics.py

      - name: Commit and push changes
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "Keine Änderungen zu committen."
          else
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/*.ics
            git commit -m "Update ICS files"
            git push
          fi
